## Shiny demonstration {.tabset .tabset-fade .tabset-pills}

</br>

---
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Task plans}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

<head>
  <style>
    body{ 
      font-size: 14px;
    }
  </style>
</head>

### Getting started

</br>

First and foremost, you need to have installed the package `shiny` and then load it using `library(shiny)`. This repo contains a number of Shiny examples. I borrowed some from [RStudio's Shiny lesson](https://shiny.rstudio.com/articles/build.html), some are from existing USGS repositories on GitHub, and some are ones I worked on myself. The following is what we will walk through for today's webinar and will hopefully serve as a good reference for the future.

### Basic apps

</br>

We will start by exploring the most bare-bones Shiny app example. You can find it in the folder `Webinar-2-27-2019/1_shiny_skeleton/`. To run any shiny app, you use `runApp` with the path to the folder containing your app files. 

</br>

```
runApp("Webinar-2-27-2019/1_shiny_skeleton/")
```

</br>

The next app example is still very simple, but shows some more features such as inputs/outputs for being reactive. The tutorial used to create this can be found here: https://shiny.rstudio.com/articles/build.html

</br>

```
runApp("Webinar-2-27-2019/2_shiny_simple/")
```

### Apps with USGS data

</br>

#### Existing USGS apps

</br>

First, install each package from GitHub. Then, you can explore each app by starting it from the console.

```
devtools::install_github('USGS-R/EGRETextra')
EGRETextra::explore_EGRET()
```

```
devtools::install_github('USGS-R/wateRuse')
wateRuse::explore_wateRuse()
```

```
devtools::install_github('USGS-R/WREG')
WREG::WREGgui()
```

```
devtools::install_github('USGS-R/toxEval')
toxEval::explore_endpoints()
```

</br>

#### Custom USGS groundwater app

I used a custom theme through the `shinythemes` package. In my UI function, I loaded the `shinythemes` package and added the argument `theme = shinytheme("yeti")`. You can find additional theme options through `shinytheme` [here](http://rstudio.github.io/shinythemes/). 

```
runApp("Webinar-2-27-2019/3_shiny_usgs_gw")
```

### Hosting apps

</br>

Our recommendation is to not build shiny apps for use-cases that will be meant for a wide public audience. Hosting shiny applications can for that type of use-case can be expensive and require overhead for handling deployment. We recommend building apps within R repositories and directing users to run two commands: install the repo and startup the shiny app (as you did with the USGS examples in the previous section). Another alternative if you want to share with non-R users and see the local R startup process as an issue is to use interactive documents, which is explained in the next section.

* Shiny Server / Shiny Server Pro: https://www.rstudio.com/products/shiny/shiny-server/
* Shinyapps.io: http://www.shinyapps.io/
* RStudio Connect (not familiar with this)
* Start from a local RStudio session

### Interactive documents

</br>

You can also take advantage of R Markdown formatting to create lightweight apps using Shiny + R Markdown. Open the file in this folder called `Webinar-2-27-2019/interactive_doc_example.Rmd` and click "Run App" to see a lightweight shiny app in action.
